# services:
#   marvel-app:
#     build: .
#     container_name: marvel-app
#     restart: always
#     networks:
#       - boltluna-net
#     env_file:
#       - .env

# networks:
#   boltluna-net:
#     external: true


services:
  marvel-app:
    build: .
    container_name: marvel-app
    restart: always
    env_file:
      - .env
    networks:
      - boltluna-net
    ports:
      - "3000:3000"   # 👈 host → container binding
